image: elixir:latest
stages:
  - mix
  - docker

variables:
  MIX_ENV: 'test'
  REGISTRY: ghcr.io

default:
  before_script:
    - mix local.rebar --force
    - mix local.hex --force
    - mix deps.get
    - mix deps.compile
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - mix.lock
      - _build
      - deps

format:
  stage: mix
  script:
    - mix format --check-formatted

test:
  stage: mix
  script:
    - mix ecto.create
    - mix ecto.migrate
    - mix test
  artifacts:
      when: always
      reports:
        junit: test/*-unit.xml

credo:
  stage: mix
  script:
    - mix credo

dialyzer:
  stage: mix
  script:
    - mix dialyzer
  only:
    - schedules

docker_build:
  stage: docker
  services:
    - docker:dind
  image: docker:cli
  before_script:
    - docker login $REGISTRY -u $REGISTRY_USER -p $REGISTRY_PASSWORD
  script:
    - docker build --pull -t "m321-chat" .
    # latest tag
    - docker tag "m321-chat" "$REGISTRY/$PROJECT_NAMESPACE/m321-chat:latest"
    - docker push "$REGISTRY/$PROJECT_NAMESPACE/m321-chat:latest"
    # version tag
    - docker tag "m321-chat" "$REGISTRY/$PROJECT_NAMESPACE/m321-chat:$CI_COMMIT_TAG"
    - docker push "$REGISTRY/$PROJECT_NAMESPACE/m321-chat:$CI_COMMIT_TAG"
  only:
    - tags
